kind: pipeline
name: default

steps:
  - name: test-online
    image: maven:3-jdk-11
    environment:
      VAULT_VERSION: 1.4.0-rc1
    commands:
      - curl -o vault_1.4.0-rc1_linux_amd64.zip https://releases.hashicorp.com/vault/1.4.0-rc1/vault_1.4.0-rc1_linux_amd64.zip
      - curl -s https://releases.hashicorp.com/vault/1.4.0-rc1/vault_1.4.0-rc1_SHA256SUMS | grep linux_amd64 | sha256sum -c
      - unzip vault_1.4.0-rc1_linux_amd64.zip
      - rm vault_1.4.0-rc1_linux_amd64.zip
      - mv vault /bin/
      - mvn clean test
    when:
      branch:
        - master
  - name: test-offline
    image: maven:3-jdk-11
    commands:
      - mvn clean test -P offline-tests
    when:
      branch:
        - develop
        - feature/*
