kind: pipeline
name: default

steps:
  - name: compile
    image: maven:3-openjdk-17
    commands:
      - mvn -B clean compile
    when:
      branch:
        - main
        - develop
        - feature/*
        - fix/*
        - release/*
  - name: unit-tests
    image: maven:3-openjdk-17
    commands:
      - mvn -B test
    when:
      branch:
        - develop
        - feature/*
        - fix/*
  - name: unit-integration-tests
    image: maven:3-openjdk-17
    environment:
      VAULT_VERSION: 1.11.2
    commands:
      - curl -s -o vault_$${VAULT_VERSION}_linux_amd64.zip https://releases.hashicorp.com/vault/$${VAULT_VERSION}/vault_$${VAULT_VERSION}_linux_amd64.zip
      - curl -s https://releases.hashicorp.com/vault/$${VAULT_VERSION}/vault_$${VAULT_VERSION}_SHA256SUMS | grep linux_amd64 | sha256sum -c
      - unzip vault_$${VAULT_VERSION}_linux_amd64.zip
      - rm vault_$${VAULT_VERSION}_linux_amd64.zip
      - mv vault /bin/
      - mvn -B -P integration-test verify
    when:
      branch:
        - main
        - release/*
