kind: pipeline
name: default

steps:
  - name: test-online
    image: maven:3-jdk-11-slim
    commands:
      - export VAULT_VERSION=1.1.3
      - wget https://releases.hashicorp.com/vault/${VAULT_VERSION}/vault_${VAULT_VERSION}_linux_amd64.zip
      - wget -q -O - https://releases.hashicorp.com/vault/${VAULT_VERSION}/vault_${VAULT_VERSION}_SHA256SUMS | grep linux_amd64 | sha256sum -c
      - unzip vault_${VAULT_VERSION}_linux_amd64.zip
      - rm vault_${VAULT_VERSION}_linux_amd64.zip
      - mv vault /bin/
      - mvn clean test
    when:
      branch:
        - master
  - name: test-offline
    image: maven:3-jdk-11-slim
    commands:
      - mvn clean test -Dtest='!HTTPVaultConnectorTest'
    when:
      branch:
        - develop
        - feature/*
