kind: pipeline
name: default

steps:
  - name: compile
    image: maven:3-jdk-11
    commands:
      - mvn -B clean compile
    when:
      branch:
        - main
        - develop
        - feature/*
        - fix/*
        - release/*
  - name: unit-tests
    image: maven:3-jdk-11
    commands:
      - mvn -B resources:testResources compiler:testCompile surefire:test -P offline-tests
    when:
      branch:
        - develop
        - feature/*
        - fix/*
  - name: unit-integration-tests
    image: maven:3-jdk-11
    environment:
      VAULT_VERSION: 1.7.0
    commands:
      - curl -s -o vault_1.7.0_linux_amd64.zip https://releases.hashicorp.com/vault/1.7.0/vault_1.7.0_linux_amd64.zip
      - curl -s https://releases.hashicorp.com/vault/1.7.0/vault_1.7.0_SHA256SUMS | grep linux_amd64 | sha256sum -c
      - unzip vault_1.7.0_linux_amd64.zip
      - rm vault_1.7.0_linux_amd64.zip
      - mv vault /bin/
      - mvn -B resources:testResources compiler:testCompile surefire:test
    when:
      branch:
        - main
        - release/*