branches:
  only:
    - master
language: java
jdk:
  - oraclejdk8
dist: trusty
env:
  - PATH=$PATH:.
before_script:
  - wget https://releases.hashicorp.com/vault/0.8.1/vault_0.8.1_linux_amd64.zip
  - unzip vault_0.8.1_linux_amd64.zip
  - rm vault_0.8.1_linux_amd64.zip
